"""empty message

Revision ID: 08d3e667d99a
Revises: 5ccea8c19f3b
Create Date: 2026-08-02 16:42:47.667149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d3e667d99a'
down_revision = '5ccea8c19f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_nos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ContactNumber', sa.String(length=50), nullable=True))
        batch_op.drop_column('PhoneNumber')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_nos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PhoneNumber', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('ContactNumber')

    # ### end Alembic commands ###
