"""Add SubjectID and GroupID to attendances

Revision ID: 11ca16f16642
Revises: ef06ce277446
Create Date: 2026-08-02 18:23:08.203699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ca16f16642'
down_revision = 'ef06ce277446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SubjectID', sa.Integer(), nullable=False))
        batch_op.alter_column('SessionID',
               existing_type=sa.INTEGER(),
               nullable=False)
        # 🛠️ បន្ថែមឈ្មោះឱ្យ foreign key ត្រង់នេះ (ជំនួសឱ្យ None)
        batch_op.create_foreign_key('fk_qr_codes_subject_id', 'subjects', ['SubjectID'], ['SubjectID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        # 🛠️ ដាក់ឈ្មោះ constraint ដូចគ្នាពេលទម្លាក់ចុះវិញ (Drop)
        batch_op.drop_constraint('fk_qr_codes_subject_id', type_='foreignkey')
        batch_op.alter_column('SessionID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('SubjectID')

    # ### end Alembic commands ###