"""Initial fresh migration with SubjectID

Revision ID: 3f2097615397
Revises: 40ee4991909d
Create Date: 2026-08-02 18:27:44.080382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2097615397'
down_revision = '40ee4991909d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        # 🛠️ ផ្លាស់ប្តូរពី False មក True ជាបណ្តោះអាសន្ន
        batch_op.add_column(sa.Column('SubjectID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_qr_codes_subject_id', 'subjects', ['SubjectID'], ['SubjectID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        # 🛠️ ដាក់ឈ្មោះ constraint ដូចគ្នាពេល drop
        batch_op.drop_constraint('fk_qr_codes_subject_id', type_='foreignkey')
        batch_op.drop_column('SubjectID')

    # ### end Alembic commands ###