"""Force fix qr_codes SubjectID column

Revision ID: 40ee4991909d
Revises: 11ca16f16642
Create Date: 2026-08-02 18:26:14.354918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ee4991909d'
down_revision = '11ca16f16642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SubjectID', sa.Integer(), nullable=False))
        batch_op.alter_column('SessionID',
               existing_type=sa.INTEGER(),
               nullable=False)
        # 🛠️ បន្ថែមឈ្មោះ 'fk_qr_codes_subject_id' ជំនួសឱ្យ None
        batch_op.create_foreign_key('fk_qr_codes_subject_id', 'subjects', ['SubjectID'], ['SubjectID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        # 🛠️ ដាក់ឈ្មោះ constraint ឱ្យស្របគ្នាពេល drop
        batch_op.drop_constraint('fk_qr_codes_subject_id', type_='foreignkey')
        batch_op.alter_column('SessionID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('SubjectID')

    # ### end Alembic commands ###