"""Initial migration

Revision ID: 5ccea8c19f3b
Revises: 
Create Date: 2026-08-01 18:05:17.807578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccea8c19f3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_nos',
    sa.Column('ContactID', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ContactID')
    )
    op.create_table('provinces',
    sa.Column('ProvinceID', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ProvinceID'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('sessions',
    sa.Column('SessionID', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Session_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('SessionID'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('user_types',
    sa.Column('TypeID', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('TypeName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('TypeID'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('classes',
    sa.Column('ClassID', sa.Integer(), nullable=False),
    sa.Column('SessionID', sa.Integer(), nullable=True),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['SessionID'], ['sessions.SessionID'], ),
    sa.PrimaryKeyConstraint('ClassID'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('districts',
    sa.Column('DistrictID', sa.Integer(), nullable=False),
    sa.Column('ProvinceID', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['ProvinceID'], ['provinces.ProvinceID'], ),
    sa.PrimaryKeyConstraint('DistrictID'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('groups',
    sa.Column('GroupID', sa.Integer(), nullable=False),
    sa.Column('SessionID', sa.Integer(), nullable=True),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('ScheduleID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SessionID'], ['sessions.SessionID'], ),
    sa.PrimaryKeyConstraint('GroupID'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('qr_codes',
    sa.Column('QrCodeID', sa.Integer(), nullable=False),
    sa.Column('SessionID', sa.Integer(), nullable=True),
    sa.Column('StartDate', sa.DateTime(), nullable=False),
    sa.Column('EndDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SessionID'], ['sessions.SessionID'], ),
    sa.PrimaryKeyConstraint('QrCodeID')
    )
    op.create_table('communes',
    sa.Column('CommuneID', sa.Integer(), nullable=False),
    sa.Column('DistrictID', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['DistrictID'], ['districts.DistrictID'], ),
    sa.PrimaryKeyConstraint('CommuneID'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('subjects',
    sa.Column('SubjectID', sa.Integer(), nullable=False),
    sa.Column('GroupID', sa.Integer(), nullable=True),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['GroupID'], ['groups.GroupID'], ),
    sa.PrimaryKeyConstraint('SubjectID'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('villages',
    sa.Column('VillageID', sa.Integer(), nullable=False),
    sa.Column('CommuneID', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['CommuneID'], ['communes.CommuneID'], ),
    sa.PrimaryKeyConstraint('VillageID'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('addresses',
    sa.Column('AddressID', sa.Integer(), nullable=False),
    sa.Column('Home', sa.String(length=50), nullable=True),
    sa.Column('Street', sa.String(length=100), nullable=True),
    sa.Column('ProvinceID', sa.Integer(), nullable=True),
    sa.Column('DistrictID', sa.Integer(), nullable=True),
    sa.Column('CommuneID', sa.Integer(), nullable=True),
    sa.Column('VillageID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CommuneID'], ['communes.CommuneID'], ),
    sa.ForeignKeyConstraint(['DistrictID'], ['districts.DistrictID'], ),
    sa.ForeignKeyConstraint(['ProvinceID'], ['provinces.ProvinceID'], ),
    sa.ForeignKeyConstraint(['VillageID'], ['villages.VillageID'], ),
    sa.PrimaryKeyConstraint('AddressID')
    )
    op.create_table('user_profiles',
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('AddressID', sa.Integer(), nullable=True),
    sa.Column('GroupID', sa.Integer(), nullable=True),
    sa.Column('ClassID', sa.Integer(), nullable=True),
    sa.Column('TypeID', sa.Integer(), nullable=True),
    sa.Column('ContactNoID', sa.Integer(), nullable=True),
    sa.Column('SubjectID', sa.Integer(), nullable=True),
    sa.Column('Code', sa.String(length=50), nullable=False),
    sa.Column('Name', sa.String(length=150), nullable=False),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('Photo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['AddressID'], ['addresses.AddressID'], ),
    sa.ForeignKeyConstraint(['ClassID'], ['classes.ClassID'], ),
    sa.ForeignKeyConstraint(['ContactNoID'], ['contact_nos.ContactID'], ),
    sa.ForeignKeyConstraint(['GroupID'], ['groups.GroupID'], ),
    sa.ForeignKeyConstraint(['SubjectID'], ['subjects.SubjectID'], ),
    sa.ForeignKeyConstraint(['TypeID'], ['user_types.TypeID'], ),
    sa.PrimaryKeyConstraint('ProfileID'),
    sa.UniqueConstraint('Code')
    )
    op.create_table('attendances',
    sa.Column('AttendanceID', sa.Integer(), nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('QrCodeID', sa.Integer(), nullable=False),
    sa.Column('ScanNumber', sa.String(length=50), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ProfileID'], ['user_profiles.ProfileID'], ),
    sa.ForeignKeyConstraint(['QrCodeID'], ['qr_codes.QrCodeID'], ),
    sa.PrimaryKeyConstraint('AttendanceID')
    )
    op.create_table('logins',
    sa.Column('LoginID', sa.Integer(), nullable=False),
    sa.Column('ProfileID', sa.Integer(), nullable=False),
    sa.Column('Full_name', sa.String(length=150), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ProfileID'], ['user_profiles.ProfileID'], ),
    sa.PrimaryKeyConstraint('LoginID'),
    sa.UniqueConstraint('ProfileID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logins')
    op.drop_table('attendances')
    op.drop_table('user_profiles')
    op.drop_table('addresses')
    op.drop_table('villages')
    op.drop_table('subjects')
    op.drop_table('communes')
    op.drop_table('qr_codes')
    op.drop_table('groups')
    op.drop_table('districts')
    op.drop_table('classes')
    op.drop_table('user_types')
    op.drop_table('sessions')
    op.drop_table('provinces')
    op.drop_table('contact_nos')
    # ### end Alembic commands ###
