"""empty message

Revision ID: 8018e27cc8a9
Revises: 3f2097615397
Create Date: 2026-08-04 21:00:20.724250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8018e27cc8a9'
down_revision = '3f2097615397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.alter_column('SessionID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('SubjectID',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('Gender')

    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.alter_column('SubjectID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('SessionID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
