"""empty message

Revision ID: ef06ce277446
Revises: 35b0de6161f2
Create Date: 2026-08-02 17:41:08.386019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef06ce277446'
down_revision = '35b0de6161f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SubjectID', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('GroupID', sa.Integer(), nullable=True))

        # 👉 ទុកតែពីរខ្សែនេះបានហើយ ដែលមានដាក់ឈ្មោះទប់ស្កាត់ error
        batch_op.create_foreign_key('fk_attendances_subject', 'subjects', ['SubjectID'], ['SubjectID'])
        batch_op.create_foreign_key('fk_attendances_group', 'groups', ['GroupID'], ['GroupID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendances_group', type_='foreignkey')
        batch_op.drop_constraint('fk_attendances_subject', type_='foreignkey')
        batch_op.drop_column('GroupID')
        batch_op.drop_column('SubjectID')

    # ### end Alembic commands ###